const FETCH_POPULAR_GIFS = 'FETCH_POPULAR_GIFS';
const FETCH_SEARCH_GIFS = 'FETCH_SEARCH_GIFS';
const FETCH_SEARCH_STICKERS = 'FETCH_SEARCH_STICKERS';
const FETCH_RANDOM_GIFS = 'FETCH_RANDOM_GIFS';
const FETCH_RANDOM_PHOTOS = 'FETCH_RANDOM_PHOTOS'

const SET_ACTIV_TAB = 'SET_ACTIV_TAB';
const CHANGE_IS_LOADING = 'CHANGE_IS_LOADING'
const CHANGE_LIMIT = 'CHANGE_LIMIT'
const SET_TITLE = 'SET_TITLE'

export { 
    FETCH_POPULAR_GIFS,
    FETCH_RANDOM_GIFS,
    FETCH_SEARCH_GIFS,
    FETCH_SEARCH_STICKERS,
    SET_ACTIV_TAB,
    FETCH_RANDOM_PHOTOS,
    CHANGE_IS_LOADING,
    CHANGE_LIMIT,
    SET_TITLE,
}